name: CI

on:
  pull-request:
    branches:
      - master

jobs:
  linter_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - name: Run result_format_checker.sh
        run: sh ./scripts/result_format_checker.sh
      - name: Run flutter analyze
        run: flutter analyze
      - name: Run flutter test
        run: flutter test
